In [10]:
pd.get_option('display.max_colwidth')

50

In [11]:
pd.set_option('display.max_colwidth', None)

### Generacion de data sintetica

In [76]:
import pandas as pd
from faker import Faker
import random

# Inicializar Faker
fake = Faker()

In [77]:
# Definiciones
nombres = fake.first_name()  #['Jose', 'Maria', 'Juan', 'Ana', 'Luis', 'Laura', 'Carlos', 'Marta', 'Javier', 'Sofia']
apellidos = fake.last_name() #['Perez', 'Gomez', 'Lopez', 'Martinez', 'Fernandez', 'Garcia', 'Rodriguez', 'Sanchez', 'Torres', 'Diaz']
seniority_levels = ['jr', 'ssr', 'sr1', 'sr2', 'sr3','sr4']
paises = ['Peru', 'Colombia', 'Ecuador', 'Argentina', 'Chile', 'Uruguay', 'Bolivia', 'Paraguay', 'Venezuela', 'Mexico']

#### Numero de registros sinteticos

In [101]:
num_records  = 10000

In [79]:
roles = [
    "Android Mobile Developer", "C++ Developer", "Cobol Developer", "Flutter Developer",
    "Game Developer", "iOS Mobile Developer", "Java Developer", ".Net Developer", 
    "NodeJs Developer", "PHP Developer", "Python Developer", "RPA Developer", 
    "Ruby Developer", "Salesforce Developer", "Sharepoint Developer", "SQL Developer",
    "Web Mobile Developer", "Web UI Developer", "Cloud Engineer", "Cybersecurity Engineer", 
    "Data Engineer","DevOps Engineer", "IOT Platform Engineer", "Test Automation Engineer"
]

In [80]:
hard_skills_final = {
    "Android Mobile Developer": [
        "Java", "Kotlin", "Flutter", "Android SDK", "XML",
        "REST APIs", "SQLite", "Gradle", "JUnit", "RxJava",
        "MVP", "MVVM", "UI/UX Design", "Firebase", "Coroutines",
        "Material Design", "Dagger", "Retrofit", "Git", "Agile",
        "Test-Driven Development", "Dependency Injection", "Performance Tuning",
        "Android Architecture Components", "Security Best Practices", 
        "Android Jetpack", "Kotlin Coroutines", "LiveData", "Data Binding", 
        "Android NDK", "Motion Layout", "Constraint Layout", "ProGuard"
    ],
    "C++ Developer": [
        "C++", "Data Structures", "Algorithms", "OOP", "Multithreading",
        "Templates", "Boost Library", "Qt Framework", "Memory Management", 
        "Design Patterns", "Standard Template Library (STL)", "Debugging",
        "Unit Testing", "Networking", "Concurrency", "File I/O",
        "CMake", "Version Control (Git)", "Cross-Platform Development", 
        "Profiling", "Compiler Optimization", "Embedded Systems", 
        "Linux Development", "Windows API", "Graphics Programming", 
        "OpenGL", "DirectX", "Game Development", "System Programming",
        "Static and Dynamic Libraries", "Automated Testing", "Code Review"
    ],
    "Cobol Developer": [
        "COBOL", "DB2", "CICS", "JCL", "VSAM",
        "SQL", "Mainframe", "IBM z/OS", "File Handling", 
        "Data Structures", "Batch Processing", "Debugging",
        "Unit Testing", "Version Control (Git)", "Agile", 
        "Micro Focus", "SoftTech", "Data Migration", 
        "Legacy Systems", "Business Logic", "Documentation", 
        "System Integration", "Performance Tuning", "Change Management", 
        "Application Development", "System Analysis", "Software Maintenance", 
        "Data Mapping", "Data Warehousing", "Data Processing", 
        "Client Interaction", "User Acceptance Testing (UAT)", "Reporting"
    ],
    "Flutter Developer": [
        "Dart", "Flutter", "RESTful APIs", "State Management", "UI/UX Design",
        "Firebase", "Animations", "Version Control (Git)", "Agile", 
        "Debugging", "Testing", "Performance Optimization", 
        "Cross-Platform Development", "Third-party Libraries", "Material Design",
        "App Deployment", "Responsive Design", "Security Best Practices",
        "Native Modules", "Platform Channels", "Custom Widgets", 
        "Accessibility Features", "Localization", "Internationalization", 
        "Continuous Integration", "Versioning", "Error Handling", 
        "Dependency Management", "Code Refactoring", "Integration Testing", 
        "User Interface Testing", "Network Connectivity", "Asynchronous Programming"
    ],
    "Game Developer": [
        "C#", "Unity", "Unreal Engine", "Game Design", "3D Modeling",
        "Animation", "Physics Simulation", "AI Programming", "Networking", 
        "Version Control (Git)", "Agile", "Debugging", 
        "Graphics Programming", "Shader Programming", "Sound Design", 
        "Game Monetization", "Performance Optimization", "User Interface Design",
        "Cross-platform Development", "VR/AR Development", "Game Analytics",
        "Gameplay Programming", "Level Design", "Storyboarding", 
        "Asset Management", "Game Testing", "Live Ops", 
        "Multiplayer Networking", "Visual Scripting", "Procedural Generation", 
        "Game Prototyping", "Game Optimization", "Physics Engines"
    ],
    "iOS Mobile Developer": [
        "Swift", "Objective-C", "iOS SDK", "Xcode", "Cocoa Touch",
        "Core Data", "RESTful APIs", "UIKit", "SwiftUI", "Auto Layout",
        "Git", "Agile", "Unit Testing", "Debugging", 
        "Performance Optimization", "App Store Submission", 
        "Third-party Libraries", "Firebase", "Push Notifications", 
        "iCloud", "Security Best Practices", "User Interface Design", 
        "Multithreading", "Animation", "Network Connectivity", 
        "User Experience (UX)", "Core Animation", "Design Patterns", 
        "Reactive Programming", "SiriKit", "Core Location", 
        "In-App Purchases", "Accessibility Features"
    ],
    "Java Developer": [
        "Java", "Spring", "Hibernate", "REST APIs", "Microservices",
        "Maven", "JUnit", "JavaFX", "JDBC", "Multi-threading",
        "Design Patterns", "SOAP", "Git", "Agile", 
        "Java EE", "Performance Tuning", "Security", 
        "JPA", "Dependency Injection", "Docker", "Kubernetes",
        "Spring Boot", "Cloud Services", "Unit Testing", 
        "Continuous Integration", "API Development", "Web Services", 
        "Data Structures", "Algorithms", "Thread Management", "XML", 
        "JSON", "Logging Frameworks", "Data Access Layer", 
        "Internationalization"
    ],
    ".Net Developer": [
        "C#", ".NET Framework", ".NET Core", "ASP.NET", "Entity Framework",
        "MVC", "REST APIs", "WCF", "LINQ", "Visual Studio",
        "Version Control (Git)", "Agile", "Unit Testing", 
        "TDD", "Debugging", "SQL Server", "Web Services",
        "Microservices", "Cloud Services (Azure)", "Security Best Practices", 
        "Dependency Injection", "Performance Optimization", 
        "Web API", "SignalR", "JavaScript", "HTML/CSS", 
        "Entity Framework Core", "DevOps", "Containerization", 
        "Application Lifecycle Management", "Code Review", "Data Structures", 
        "Design Patterns", "User Authentication"
    ],
    "NodeJs Developer": [
        "Node.js", "JavaScript", "Express.js", "REST APIs", "MongoDB",
        "Socket.io", "TypeScript", "NPM", "JWT", "SQL",
        "Git", "Agile", "Debugging", "Performance Optimization",
        "Microservices", "Docker", "Kubernetes", "GraphQL",
        "Unit Testing", "Mocha", "Chai", "Postman",
        "Redis", "AWS", "Error Handling", "Asynchronous Programming",
        "Middleware", "Security Best Practices", "API Development",
        "WebSockets", "CI/CD", "Version Control", "Data Structures",
        "Event-Driven Architecture", "Logging Frameworks", "HTML/CSS",
        "Frontend Frameworks (React/Vue)"
    ],
    "PHP Developer": [
        "PHP", "Laravel", "Symfony", "REST APIs", "MySQL",
        "Composer", "HTML", "CSS", "JavaScript", "Git",
        "Agile", "Debugging", "Version Control", "Unit Testing",
        "Frameworks (CodeIgniter)", "Web Services", "Security Best Practices",
        "MVC Architecture", "Error Handling", "Performance Optimization",
        "Object-Oriented Programming", "Composer", "XML", "JSON",
        "API Development", "Database Design", "Caching Techniques",
        "Session Management", "Data Structures", "Command Line Interface (CLI)",
        "Integration with Third-party Services", "Continuous Integration",
        "User Authentication"
    ],
    "Python Developer": [
        "Python", "Django", "Flask", "REST APIs", "Data Analysis",
        "Machine Learning", "Pandas", "NumPy", "Matplotlib", "SQL",
        "Git", "Agile", "Unit Testing", "Debugging",
        "Web Scraping", "Selenium", "Data Visualization",
        "Concurrency", "Docker", "APIs", "Cloud Services",
        "Jupyter Notebooks", "Data Engineering", "Data Structures",
        "Algorithms", "Data Mining", "Natural Language Processing (NLP)",
        "Spark", "Pytorch", "TensorFlow", "Data Quality Assessment",
        "Security Best Practices"
    ],
    "RPA Developer": [
        "UiPath", "Blue Prism", "Automation Anywhere", "Python", "Java",
        "REST APIs", "Scripting", "Data Manipulation", "SQL", "Excel VBA",
        "Debugging", "Version Control", "Agile", "Business Process Mapping",
        "Workflow Design", "Exception Handling", "Testing Automation",
        "Security Best Practices", "Change Management", "Data Extraction",
        "Integration with Third-party Applications", "Performance Monitoring",
        "Process Analysis", "Documentation", "User Training",
        "Continuous Improvement", "Robotic Process Automation Frameworks",
        "Business Intelligence Tools", "Data Quality Management",
        "Client Interaction", "Reporting", "Task Automation"
    ],
    "Ruby Developer": [
        "Ruby", "Ruby on Rails", "REST APIs", "SQL", "JavaScript",
        "HTML", "CSS", "Git", "Agile", "Debugging",
        "Performance Optimization", "Testing Frameworks (RSpec)", "MVC Architecture",
        "Active Record", "Web Services", "Security Best Practices",
        "Version Control", "API Development", "Gem Management",
        "Data Structures", "Object-Oriented Programming", "Middleware",
        "Deployment Techniques", "Continuous Integration", "User Authentication",
        "Caching Techniques", "Error Handling", "Data Migration",
        "Database Design", "Task Scheduling", "Front-end Frameworks",
        "Responsive Design", "Integration with Third-party APIs"
    ],
    "Salesforce Developer": [
        "Salesforce Apex", "Visualforce", "Lightning Components", "REST APIs", "SOQL",
        "Salesforce CRM", "Data Migration", "Git", "Agile", "Debugging",
        "Version Control", "Security Best Practices", "Custom Objects",
        "Triggers", "Workflows", "Process Builder", "Reports and Dashboards",
        "User Interface Design", "Integration with Third-party Services",
        "Deployment Techniques", "Change Sets", "Data Modeling",
        "User Authentication", "Lightning Web Components", "API Development",
        "Salesforce DX", "Testing Frameworks", "Data Structures",
        "Business Process Automation", "Community Cloud", "Service Cloud",
        "Sales Cloud"
    ],
    "Sharepoint Developer": [
        "SharePoint Framework (SPFx)", "JavaScript", "HTML", "CSS", "REST APIs",
        "C#", "ASP.NET", "PowerShell", "SQL Server", "Git",
        "Agile", "Debugging", "Version Control", "Custom Web Parts",
        "Workflow Automation", "SharePoint Designer", "Microsoft Flow",
        "Office 365", "Business Intelligence", "User Interface Design",
        "Data Migration", "Security Best Practices", "Integration with Third-party Services",
        "Information Architecture", "Content Management", "User Authentication",
        "SharePoint Online", "Team Sites", "Document Libraries",
        "Performance Optimization", "Database Design", "Testing Automation"
    ],
    "SQL Developer": [
        "SQL", "PL/SQL", "T-SQL", "Database Design", "Data Modeling",
        "Stored Procedures", "Triggers", "Query Optimization", "ETL",
        "Data Warehousing", "Version Control", "Debugging", "Agile",
        "Data Migration", "Data Quality Management", "Backup and Recovery",
        "Performance Tuning", "Security Best Practices", "Indexing",
        "Database Administration", "Reporting Tools", "Integration with Third-party Tools",
        "Data Analysis", "Data Structures", "NoSQL Databases", "MySQL",
        "Oracle Database", "SQL Server", "PostgreSQL", "Data Visualization",
        "Business Intelligence Tools", "Data Governance"
    ],
       "Web Mobile Developer": [
        "HTML", "CSS", "JavaScript", "React Native", "Flutter",
        "REST APIs", "Responsive Design", "Frontend Frameworks", "Git", "Agile",
        "Debugging", "Performance Optimization", "Cross-Browser Compatibility",
        "Version Control", "UI/UX Design", "Mobile First Design",
        "Local Storage", "Service Workers", "Progressive Web Apps (PWAs)",
        "Authentication Mechanisms", "Accessibility Standards", "Testing Frameworks",
        "Continuous Integration/Continuous Deployment (CI/CD)", "Code Review",
        "State Management", "GraphQL", "WebSockets", "Data Structures",
        "Application Security", "Third-party Libraries", "Network Communication",
        "Deployment Techniques", "User Interface Testing", "Analytics Integration"
    ],
    "Web UI Developer": [
        "HTML", "CSS", "JavaScript", "React", "Vue.js",
        "Angular", "Responsive Design", "UI/UX Design", "Git", "Agile",
        "Debugging", "Performance Optimization", "Version Control",
        "Cross-Browser Compatibility", "Animations", "Accessibility Standards",
        "Front-End Frameworks", "CSS Preprocessors (Sass, LESS)", "REST APIs",
        "Testing Frameworks (Jest, Mocha)", "Web Design Principles", 
        "User Interaction Design", "Progressive Enhancement", "SEO Best Practices",
        "Content Management Systems (CMS)", "Web Standards", "State Management",
        "Microinteractions", "Design Systems", "Figma/Adobe XD", "Color Theory",
        "Typography", "Image Optimization"
    ],
    "Cloud Engineer": [
        "AWS", "Azure", "Google Cloud Platform", "Cloud Architecture", "DevOps",
        "Infrastructure as Code (IaC)", "Docker", "Kubernetes", "CI/CD", "Networking",
        "Security Best Practices", "Serverless Computing", "Virtualization",
        "Monitoring and Logging", "Data Storage Solutions", "Cloud Migration",
        "Database Management", "API Management", "Cost Optimization",
        "Backup and Recovery", "Disaster Recovery Planning", "Configuration Management",
        "Load Balancing", "Performance Tuning", "Scripting (Python, Bash)",
        "Agile", "Version Control (Git)", "Automation Tools",
        "Cloud Security", "Service Mesh", "Event-Driven Architecture",
        "Application Networking", "Resource Allocation"
    ],
    "Cybersecurity Engineer": [
        "Network Security", "Application Security", "Threat Modeling", "Risk Assessment",
        "Penetration Testing", "Incident Response", "Firewalls", "Intrusion Detection Systems (IDS)",
        "Security Information and Event Management (SIEM)", "Encryption Techniques",
        "Vulnerability Assessment", "Malware Analysis", "Security Auditing",
        "Compliance Standards (ISO, NIST)", "Security Policies", "Identity and Access Management (IAM)",
        "Data Loss Prevention (DLP)", "Incident Management", "Forensics",
        "Network Protocols", "Scripting (Python, PowerShell)", "Agile",
        "DevSecOps", "Cloud Security", "Endpoint Protection",
        "Security Awareness Training", "Security Frameworks (CIS, OWASP)",
        "Authentication Mechanisms", "Data Protection", "Mobile Security",
        "Application Hardening", "Threat Intelligence"
    ],
    "Data Engineer": [
        "Data Warehousing", "ETL Processes", "SQL", "Python", "Apache Spark",
        "Hadoop", "Data Modeling", "NoSQL Databases", "Data Lakes", "Data Pipeline Development",
        "Cloud Data Solutions (AWS, Azure, GCP)", "Data Quality Management", "Data Governance",
        "Big Data Technologies", "Data Integration Tools", "Version Control (Git)",
        "Scripting (Bash, Python)", "Apache Kafka", "Machine Learning Basics",
        "Data Visualization Tools (Tableau, Power BI)", "Agile", "Data Security",
        "Performance Tuning", "Data Architecture", "Testing and Validation",
        "Metadata Management", "Data Transformation", "Data Cataloging",
        "Analytics Integration", "Business Intelligence", "API Development"
    ],
    "DevOps Engineer": [
        "Continuous Integration/Continuous Deployment (CI/CD)", "Docker", "Kubernetes", "AWS", "Azure",
        "Infrastructure as Code (IaC)", "Version Control (Git)", "Scripting (Bash, Python)",
        "Monitoring and Logging", "Configuration Management", "Agile",
        "Networking", "Cloud Services", "Automation Tools", "Server Management",
        "Database Management", "Release Management", "Microservices Architecture",
        "Security Best Practices", "Disaster Recovery", "Performance Tuning",
        "Load Balancing", "Testing Automation", "API Management", "Collaboration Tools",
        "Change Management", "Error Tracking", "Application Performance Monitoring (APM)",
        "Site Reliability Engineering (SRE)", "Incident Management", "Custom Scripts",
        "Backup Strategies", "User Access Control"
    ],
    "IOT Platform Engineer": [
        "IoT Protocols (MQTT, CoAP)", "Embedded Systems", "Device Management", "Cloud Computing",
        "Data Analytics", "Network Security", "Sensor Technologies", "Data Processing",
        "Edge Computing", "API Development", "Scripting (Python, JavaScript)", "Version Control",
        "Agile", "Big Data Technologies", "Microservices Architecture",
        "Database Management", "Interoperability Standards", "Cloud Platforms (AWS IoT, Azure IoT)",
        "Real-time Data Processing", "User Authentication", "Data Visualization",
        "Remote Device Monitoring", "Lifecycle Management", "Firmware Development",
        "Security Best Practices", "Testing and Validation", "Device Connectivity",
        "Telemetry", "Analytics Integration", "Deployment Techniques",
        "User Interface Design"
    ],
    "Test Automation Engineer": [
        "Selenium", "JUnit", "TestNG", "Cypress", "Appium",
        "Python", "Java", "JavaScript", "API Testing", "Version Control (Git)",
        "Agile", "CI/CD", "Performance Testing", "Debugging",
        "Behavior-Driven Development (BDD)", "Framework Development", "Continuous Testing",
        "Data-Driven Testing", "Test Case Design", "Test Management Tools",
        "Automation Strategy", "Integration Testing", "User Interface Testing",
        "Security Testing", "Load Testing", "Regression Testing", "Scripting",
        "Version Control", "Reporting Tools", "Test Environment Setup",
        "Defect Tracking", "Mocking Frameworks", "Cross-Browser Testing",
        "Cloud Testing"
    ]
}

In [81]:
soft_skills = [
    "Communication", "Leadership", "Problem Solving", "Teamwork", 
    "Emotional Intelligence", "Adaptability", "Time Management", 
    "Critical Thinking", "Creativity", "Attention to Detail",
    "Conflict Resolution", "Negotiation", "Decision Making", 
    "Collaboration", "Responsibility", "Empathy", "Self-Motivation",
    "Stress Management", "Public Speaking", "Networking", "Mentoring",
    "Flexibility", "Positivity", "Interpersonal Skills", "Cultural Awareness",
    "Active Listening", "Persuasion", "Influencing", "Relationship Building",
    "Trustworthiness", "Integrity", "Work Ethic", "Initiative",
    "Analytical Thinking", "Resilience", "Motivation", "Coaching",
    "Delegation", "Creativity", "Visionary Thinking", "Change Management",
    "Goal Setting", "Resourcefulness", "Critical Observation", 
    "Open-mindedness", "Self-Regulation", "Crisis Management", 
    "Feedback Acceptance", "Humility", "Conflict Management", 
    "Social Skills", "Networking Skills", "Customer Service", 
    "Public Relations", "Presentation Skills", "Writing Skills", 
    "Research Skills", "Strategic Thinking", "Entrepreneurial Mindset",
    "Task Prioritization", "Time Optimization", "Self-Discipline",
    "Adaptability to Change", "Ethical Judgment", "Civic Responsibility",
    "Global Awareness", "Scientific Thinking", "Cognitive Flexibility",
    "Stress Resilience", "Time Awareness", "Crisis Communication",
    "Authenticity", "Intuition", "Self-Confidence", "Visionary Leadership",
    "Service Orientation", "Team Building", "Process Improvement",
    "Problem Analysis", "Learning Agility", "Intellectual Curiosity",
    "Technology Savvy", "Civic Engagement", "Diversity Awareness",
    "Interpersonal Communication", "Situational Awareness", "Risk Management",
    "Data Interpretation", "Innovation", "Client Management", 
    "Resource Allocation", "Quality Assurance", "Performance Management",
    "Motivational Skills", "Facilitation Skills", "Cultural Competence",
    "Strategic Communication", "Change Facilitation", "Negotiation Tactics",
    "Work-Life Balance", "Inclusivity", "Professionalism", 
    "Trust Building", "Emotional Resilience", "Workplace Culture Awareness",
    "Mentoring Skills", "Social Intelligence", "Virtual Collaboration",
    "Feedback Delivery", "Personality Awareness"
]

In [95]:
import pandas as pd
import random

# Función para asignar puntuaciones de habilidades según seniority
def generate_skills_(role, seniority):
    # Definir la cantidad de hard skills a seleccionar según el nivel de seniority
    if seniority in ['jr', 'ssr']:
        hard_count = 5
    elif seniority in ['sr1', 'sr2']:
        hard_count = 10
    elif seniority in ['sr3', 'sr4']:
        hard_count = 14  # Mayor cantidad de habilidades duras

    #hard = random.sample(hard_skills_final[role], k=min(hard_count, len(hard_skills_final[role])))
    #hard = random.sample(hard_skills_final.get(role, []), k=min(hard_count, len(hard_skills_final.get(role, []))))
    hard = random.sample(hard_skills_final[role], k=min(hard_count, len(hard_skills_final[role])))

    # Definir la cantidad de soft skills a seleccionar según el nivel de seniority
    if seniority in ['jr', 'ssr']:
        soft_count = 5
    elif seniority in ['sr1', 'sr2']:
        soft_count = 12
    elif seniority in ['sr3', 'sr4']:
        soft_count = 15  # Mayor cantidad de habilidades blandas

    #soft = random.sample(soft_skills, k=min(soft_count, len(soft_skills)))
    #soft = random.sample(soft_skills, k=min(soft_count, len(soft_skills)))
    soft = random.sample(soft_skills, k=min(soft_count, len(soft_skills)))
    """
    # Asignar puntuaciones
    if seniority == 'jr':
        hard_scores = [f"{skill}: 1" for skill in hard]
        soft_scores = [f"{skill}: 1" for skill in soft]
    elif seniority == 'ssr':
        hard_scores = [f"{skill}: {random.choice([1, 2])}" for skill in hard]
        soft_scores = [f"{skill}: {random.choice([1, 2])}" for skill in soft]
    elif seniority == 'sr1':
        hard_scores = [f"{skill}: {random.choice([1, 3])}" for skill in hard]
        soft_scores = [f"{skill}: {random.choice([1, 3])}" for skill in soft]
    elif seniority == 'sr2':
        hard_scores = [f"{skill}: {random.choice([1, 4])}" for skill in hard]
        soft_scores = [f"{skill}: {random.choice([1, 4])}" for skill in soft]
    elif seniority == 'sr3':
        hard_scores = [f"{skill}: {random.choice([2, 5])}" for skill in hard]
        soft_scores = [f"{skill}: {random.choice([2, 5])}" for skill in soft]
    elif seniority == 'sr4':
        hard_scores = [f"{skill}: {random.choice([3, 5])}" for skill in hard]
        soft_scores = [f"{skill}: {random.choice([3, 5])}" for skill in soft]
    """

    # Asignar puntuaciones
    score_mapping = {
        'jr': (1, 1),
        'ssr': (1, 2),
        'sr1': (1, 3),
        'sr2': (1, 4),
        'sr3': (2, 5),
        'sr4': (3, 5)
    }

    hard_scores = [f"{skill}: {random.choice(range(score_mapping[seniority][0], score_mapping[seniority][1] + 1))}" for skill in hard]
    soft_scores = [f"{skill}: {random.choice(range(score_mapping[seniority][0], score_mapping[seniority][1] + 1))}" for skill in soft]

    return {
        'hard': hard_scores,
        'soft': soft_scores
    }
    
    #return {'hard': ', '.join(hard_scores), 'soft': ', '.join(soft_scores)}

In [96]:
# Generar datos sintéticos
data = []
for _ in range(num_records):

    nombre = fake.first_name()
    apellido = fake.last_name()
    codigo = fake.unique.random_int(min=10000000, max=99999999)
    #nombre = random.choice(nombres)
    #apellido = random.choice(apellidos)
    #codigo = random.randint(10000000, 99999999)
    pais = random.choice(paises)
    rol = random.choice(roles)
    seniority = random.choice(['jr', 'ssr', 'sr1', 'sr2', 'sr3'])
    skills = generate_skills_(rol, seniority)
    
    data.append({
        'nombre': nombre,
        'apellido': apellido,
        'codigo': codigo,
        'pais': pais,
        'rol': rol,
        'seniority': seniority,
        'skills': skills
    })

df_ = pd.DataFrame(data)

print(df_.head())

     nombre apellido    codigo       pais                    rol seniority  \
0    Jaclyn  Stanley  79218551       Peru         Java Developer       ssr
1  Jennifer    Ortiz  80201916     Mexico  IOT Platform Engineer        jr
2     Holly   Watson  32079276   Colombia   Web Mobile Developer       ssr
3    Donald    Brown  29341234  Venezuela         Ruby Developer        jr
4    Robert   Wagner  21992168    Uruguay        Cobol Developer       sr1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          skills
0                                                                                                                                                                                                                                                                {'hard': ['Docker: 2', 'Data Access Layer: 1', 'Performance Tuning: 2', 'XML: 1', 'Data Structures: 2'], 'soft': ['Emotional Intelligence: 1', 'Interpersonal Communication: 2', 'Customer Service: 2', 'Writing Skills: 2', 'Influencing: 2']}
1                                                                                                                                                                                                                               {'hard': ['Device Connectivity: 1', 'Data Analytics: 1', 'IoT Protocols (MQTT, CoAP): 1', 'Testing and Validation: 1', 'User Interface Design: 1'], 'soft': ['Negotiation: 1', 'Writing Skills: 1', 'Mentoring Skills: 1', 'Adaptability to Change: 1', 'Networking Skills: 1']}
2                                                                                                                                                                                                                                        {'hard': ['GraphQL: 2', 'React Native: 2', 'HTML: 1', 'Continuous Integration/Continuous Deployment (CI/CD): 2', 'Version Control: 2'], 'soft': ['Social Intelligence: 2', 'Integrity: 1', 'Negotiation Tactics: 1', 'Time Optimization: 1', 'Presentation Skills: 1']}
3                                                                                                                                                                                                                                                {'hard': ['Deployment Techniques: 1', 'Ruby: 1', 'Object-Oriented Programming: 1', 'REST APIs: 1', 'Data Migration: 1'], 'soft': ['Social Skills: 1', 'Critical Observation: 1', 'Adaptability to Change: 1', 'Feedback Acceptance: 1', 'Ethical Judgment: 1']}
4  {'hard': ['Reporting: 2', 'Data Warehousing: 2', 'VSAM: 3', 'Batch Processing: 2', 'User Acceptance Testing (UAT): 1', 'System Integration: 1', 'COBOL: 3', 'Data Migration: 3', 'SoftTech: 3', 'Business Logic: 2'], 'soft': ['Facilitation Skills: 1', 'Emotional Intelligence: 1', 'Persuasion: 1', 'Positivity: 2', 'Diversity Awareness: 1', 'Resourcefulness: 1', 'Writing Skills: 2', 'Trust Building: 1', 'Flexibility: 1', 'Self-Regulation: 1', 'Public Relations: 1', 'Situational Awareness: 1']}

In [99]:
df_.count()

nombre       1000
apellido     1000
codigo       1000
pais         1000
rol          1000
seniority    1000
skills       1000
dtype: int64

In [97]:
df_

,nombre,apellido,codigo,pais,rol,seniority,skills
0,Jaclyn,Stanley,79218551,Peru,Java Developer,ssr,"{'hard': ['Docker: 2', 'Data Access Layer: 1', 'Performance Tuning: 2', 'XML: 1', 'Data Structures: 2'], 'soft': ['Emotional Intelligence: 1', 'Interpersonal Communication: 2', 'Customer Service: 2', 'Writing Skills: 2', 'Influencing: 2']}"
1,Jennifer,Ortiz,80201916,Mexico,IOT Platform Engineer,jr,"{'hard': ['Device Connectivity: 1', 'Data Analytics: 1', 'IoT Protocols (MQTT, CoAP): 1', 'Testing and Validation: 1', 'User Interface Design: 1'], 'soft': ['Negotiation: 1', 'Writing Skills: 1', 'Mentoring Skills: 1', 'Adaptability to Change: 1', 'Networking Skills: 1']}"
2,Holly,Watson,32079276,Colombia,Web Mobile Developer,ssr,"{'hard': ['GraphQL: 2', 'React Native: 2', 'HTML: 1', 'Continuous Integration/Continuous Deployment (CI/CD): 2', 'Version Control: 2'], 'soft': ['Social Intelligence: 2', 'Integrity: 1', 'Negotiation Tactics: 1', 'Time Optimization: 1', 'Presentation Skills: 1']}"
3,Donald,Brown,29341234,Venezuela,Ruby Developer,jr,"{'hard': ['Deployment Techniques: 1', 'Ruby: 1', 'Object-Oriented Programming: 1', 'REST APIs: 1', 'Data Migration: 1'], 'soft': ['Social Skills: 1', 'Critical Observation: 1', 'Adaptability to Change: 1', 'Feedback Acceptance: 1', 'Ethical Judgment: 1']}"
4,Robert,Wagner,21992168,Uruguay,Cobol Developer,sr1,"{'hard': ['Reporting: 2', 'Data Warehousing: 2', 'VSAM: 3', 'Batch Processing: 2', 'User Acceptance Testing (UAT): 1', 'System Integration: 1', 'COBOL: 3', 'Data Migration: 3', 'SoftTech: 3', 'Business Logic: 2'], 'soft': ['Facilitation Skills: 1', 'Emotional Intelligence: 1', 'Persuasion: 1', 'Positivity: 2', 'Diversity Awareness: 1', 'Resourcefulness: 1', 'Writing Skills: 2', 'Trust Building: 1', 'Flexibility: 1', 'Self-Regulation: 1', 'Public Relations: 1', 'Situational Awareness: 1']}"
...,...,...,...,...,...,...,...
995,Russell,Freeman,97786511,Ecuador,Web Mobile Developer,sr1,"{'hard': ['Authentication Mechanisms: 3', 'Testing Frameworks: 2', 'WebSockets: 1', 'Cross-Browser Compatibility: 2', 'Network Communication: 2', 'Mobile First Design: 2', 'State Management: 1', 'Application Security: 3', 'React Native: 1', 'Git: 2'], 'soft': ['Relationship Building: 3', 'Client Management: 3', 'Risk Management: 1', 'Personality Awareness: 3', 'Positivity: 2', 'Creativity: 2', 'Negotiation Tactics: 1', 'Adaptability to Change: 2', 'Empathy: 3', 'Coaching: 3', 'Visionary Thinking: 1', 'Technology Savvy: 3']}"
996,Rose,Green,88688910,Peru,Game Developer,jr,"{'hard': ['Multiplayer Networking: 1', 'Game Analytics: 1', 'Version Control (Git): 1', 'Physics Simulation: 1', 'Shader Programming: 1'], 'soft': ['Integrity: 1', 'Situational Awareness: 1', 'Change Management: 1', 'Diversity Awareness: 1', 'Emotional Intelligence: 1']}"
997,Ryan,Ruiz,24704562,Bolivia,RPA Developer,sr1,"{'hard': ['Automation Anywhere: 1', 'REST APIs: 3', 'Scripting: 1', 'Robotic Process Automation Frameworks: 2', 'UiPath: 2', 'Data Manipulation: 2', 'Testing Automation: 1', 'Debugging: 2', 'Data Quality Management: 2', 'Excel VBA: 1'], 'soft': ['Mentoring Skills: 2', 'Trust Building: 2', 'Influencing: 3', 'Strategic Thinking: 2', 'Risk Management: 2', 'Time Optimization: 1', 'Time Awareness: 1', 'Research Skills: 3', 'Social Skills: 3', 'Civic Engagement: 3', 'Civic Responsibility: 1', 'Service Orientation: 2']}"
998,David,Lutz,91068242,Ecuador,DevOps Engineer,sr3,"{'hard': ['AWS: 4', 'Custom Scripts: 2', 'Configuration Management: 5', 'Server Management: 5', 'Site Reliability Engineering (SRE): 2', 'Release Management: 3', 'Incident Management: 2', 'Change Management: 5', 'Database Management: 3', 'Security Best Practices: 2', 'API Management: 2', 'User Access Control: 4', 'Azure: 4', 'Error Tracking: 4'], 'soft': ['Writing Skills: 2', 'Public Speaking: 4', 'Problem Analysis: 4', 'Interpersonal Communication: 3', 'Mentoring Skills: 3', 'Risk Management: 5', 'Positivity: 2', 'Work-Life Balance: 3', 'Relationship Building: 2', 'Negotiation: 3', 'Interpersonal Skills: 2', 'Conflict Management: 5', 'Initiative: 4', 'Networking Skills: 5', 'Civic Engagement: 2']}"
999,Jennifer,Hernandez,86151530,Ecuador,Cloud Engineer,jr,"{'hard': ['Database Management: 1', 'Resource Allocation: 1', 'Automation Tools: 1', 'DevOps: 1', 'Scripting (Python, Bash): 1'], 'soft': ['Motivation: 1', 'Active Listening: 1', 'Innovation: 1', 'Self-Regulation: 1', 'Resource Allocation: 1']}"

Older

In [98]:
df

,nombre,apellido,codigo,pais,rol,seniority,skills
0,Kevin,White,77997750,Venezuela,Cloud Engineer,sr2,"{'hard': 'Configuration Management: 1, Cost Optimization: 1, Agile: 2, DevOps: 3, Kubernetes: 1, Backup and Recovery: 2, Networking: 1, Automation Tools: 2, Infrastructure as Code (IaC): 1, AWS: 2', 'soft': 'Presentation Skills: 2, Interpersonal Skills: 2, Goal Setting: 2, Self-Confidence: 3, Conflict Resolution: 1, Virtual Collaboration: 4, Critical Thinking: 3, Resourcefulness: 3, Teamwork: 4, Negotiation: 2, Strategic Communication: 4, Stress Management: 3'}"
1,Kevin,Anderson,17591139,Peru,SQL Developer,ssr,"{'hard': 'Indexing: 2, Stored Procedures: 1, Data Visualization: 2, Integration with Third-party Tools: 2, PostgreSQL: 2', 'soft': 'Process Improvement: 1, Adaptability: 2, Persuasion: 2, Interpersonal Communication: 2, Emotional Resilience: 2'}"
2,Scott,Gonzalez,32529385,Colombia,SQL Developer,ssr,"{'hard': 'Data Structures: 1, SQL Server: 1, Database Administration: 1, NoSQL Databases: 2, Data Migration: 1', 'soft': 'Time Management: 2, Creativity: 1, Work-Life Balance: 1, Emotional Intelligence: 1, Critical Observation: 2'}"
3,Ryan,Nichols,68596859,Mexico,Cloud Engineer,sr1,"{'hard': 'API Management: 1, Disaster Recovery Planning: 1, Cloud Security: 3, DevOps: 3, Load Balancing: 1, CI/CD: 3, Infrastructure as Code (IaC): 3, Application Networking: 3, Database Management: 1, Resource Allocation: 3', 'soft': 'Workplace Culture Awareness: 2, Decision Making: 3, Technology Savvy: 3, Social Intelligence: 3, Ethical Judgment: 3, Emotional Resilience: 2, Integrity: 3, Self-Regulation: 1, Collaboration: 1, Motivation: 1, Situational Awareness: 2, Mentoring Skills: 1'}"
4,Sonya,Tate,52119474,Colombia,Salesforce Developer,jr,"{'hard': 'Change Sets: 1, Service Cloud: 1, Security Best Practices: 1, Deployment Techniques: 1, Custom Objects: 1', 'soft': 'Mentoring: 1, Public Speaking: 1, Relationship Building: 1, Positivity: 1, Motivation: 1'}"
...,...,...,...,...,...,...,...
995,Rebecca,King,49334523,Paraguay,Ruby Developer,sr3,"{'hard': 'Version Control: 2, User Authentication: 5, Security Best Practices: 5, JavaScript: 5, Responsive Design: 3, Data Structures: 5, Object-Oriented Programming: 2, Front-end Frameworks: 5, SQL: 4, Continuous Integration: 4, Database Design: 5, API Development: 3, CSS: 4, Caching Techniques: 4', 'soft': 'Active Listening: 5, Facilitation Skills: 5, Collaboration: 3, Intuition: 4, Persuasion: 5, Networking Skills: 3, Feedback Acceptance: 3, Responsibility: 3, Motivation: 3, Cultural Awareness: 2, Self-Discipline: 2, Customer Service: 2, Emotional Intelligence: 4, Research Skills: 5, Situational Awareness: 4'}"
996,Mary,Green,92879456,Mexico,Data Engineer,ssr,"{'hard': 'ETL Processes: 2, Python: 1, Data Transformation: 2, Data Security: 2, Agile: 2', 'soft': 'Strategic Thinking: 2, Leadership: 2, Professionalism: 2, Stress Management: 2, Positivity: 1'}"
997,Kelly,Charles,41401187,Colombia,Data Engineer,sr2,"{'hard': 'Version Control (Git): 3, Data Quality Management: 1, Data Modeling: 1, Data Pipeline Development: 4, Performance Tuning: 2, Apache Spark: 3, NoSQL Databases: 4, Data Governance: 1, Business Intelligence: 2, Metadata Management: 2', 'soft': 'Task Prioritization: 2, Emotional Intelligence: 1, Networking: 2, Self-Discipline: 2, Quality Assurance: 3, Visionary Leadership: 3, Empathy: 3, Work-Life Balance: 1, Ethical Judgment: 1, Civic Responsibility: 2, Team Building: 2, Integrity: 2'}"
998,Stephanie,Trujillo,46268444,Venezuela,Game Developer,jr,"{'hard': 'Live Ops: 1, Visual Scripting: 1, Level Design: 1, Game Prototyping: 1, 3D Modeling: 1', 'soft': 'Performance Management: 1, Adaptability to Change: 1, Delegation: 1, Quality Assurance: 1, Technology Savvy: 1'}"
999,Christian,Odonnell,57621408,Mexico,Cobol Developer,jr,"{'hard': 'Unit Testing: 1, JCL: 1, Performance Tuning: 1, File Handling: 1, Reporting: 1', 'soft': 'Cognitive Flexibility: 1, Presentation Skills: 1, Interpersonal Skills: 1, Inclusivity: 1, Networking Skills: 1'}"

Guardamos el archivo

In [100]:
from datetime import datetime

# Getting the current date and time
dt = datetime.now()

dt_ = dt.strftime("%d-%m-%Y_%H_%M_%S_%f")
file_name  =f'output-data-sintetica/skills_data-{dt_}.csv'


df_.to_csv(file_name, index=False)

print(f"El DataFrame ha sido guardado como {file_name}'")

El DataFrame ha sido guardado como output-data-sintetica/skills_data-25-11-2024_18_28_43_342293.csv'